# docker-compose.yml

version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
